"(Insulting the Revolutionary Guards)"
"(Hello!  This user is doing illegal things.  This user was created with the aim of insulting women and publishing personal information without their consent. He is hurting children.  And Rubika users are suing this user and demanding it be blocked, forcing users to remove Rubika. This user's activities violate human rights laws and attempt to spread a culture of anti-women activism. We thank Rubika and the intelligent support team.  We request to block and delete this user who is a #fake user account as soon as possible. He said that he will close his account. Thanks for the support.)"
"(fake account)"
"(hack)"
"(obscenity)"
"(Spam)"
"(Block fake account)"
"(sex video in account rubika.ir)"
"(Isis)"
