"(Insulting the religion of Islam and its sanctities)"
"(Atheistic content and against Islamic standards)"
"(Content against Islamic holy things)"
"(Instrumental use of people (both men and women) in images and content, insulting and insulting women, promoting illegitimate and illegal rituals and luxuries)"
"(Inciting, encouraging, persuading, threatening or enticing people to access obscene and vulgar content)"
"(Publication, distribution and trading of content that violates public modesty. (vulgar and obscene)"
"(Content against modesty and public morality)"
"(Encouraging, encouraging, persuading, threatening or inviting corruption and prostitution and committing crimes against chastity or sexual perversions)"
"(Spreading obscenity and obscenities)"
